### DISCUSSION TITLE
Build system & cargo manifest

### DISCUSSION THREAD

**Discussion by o-smirnov** [SpheMakh/Stimela#696] [Ideas]
Continuing the discussion from #637.

@SpheMakh I pushed some initial revisions to configuratt, see https://github.com/ratt-ru/Stimela/commit/2021dc57dd78b1a9400fcc8cc7b254145eb02e4c. Quoting the commit message:

* load image and cab info from yaml files at startup using OmegaConf
* add stimela.config module, a local config file (``~/.config/stimela.conf``), and "stimela config" subcommand
* refactor individual sub-commands into stimela.commands.*
* use standard ArgumentParser facilities for sub-command parsers
* refactor contaioner backends into stimela.backends.*
* reimplement "stimela images" to interrogate docker directly for available images
* reimplement "stimela build", using the new OmegaConf system to get build info
* implement "stimela push"

Please take a look before too long so that our thinking stays in sync. Note that this pretty much implements #692, albeit only for docker for now. In particular, ``stimela images``, ``build`` and ``push`` now works with the new config.

**Comment by o-smirnov** [comment]
I realized that if you ship multiple images like so:
```yml
name: shadems

images:   # image versions (tags) to be built
  0.5.0:  
    dockerfile: Dockerfile       
  0.4.0:  # key is version/tag
    dockerfile: Dockerfile.v040     
```
...then you need an obvious mechanism to select a default image, when the recipe does not specify a version number. The obvious suggestion is to select the highest version. (Comparing semvers properly: https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python/21065570)

Then, in development I often find myself building "test" images with pre-release or branch versions of packages, we don't want those ever selected by default. I have added a ``production`` option (default Trrue). So:

```yml
images:   # image versions (tags) to be built
  0.6.test:  
    dockerfile: Dockerfile.v06test
    production: false       
  0.5.0:  
    dockerfile: Dockerfile       
  0.4.0:  # key is version/tag
    dockerfile: Dockerfile.v040     
```

The default image version should then be the highest-numbered production version. NB: need to modify ``stimela build`` to add a "production" label to the image.
