### DISCUSSION TITLE
Parameter validation in the presence of {}-substitutions

### DISCUSSION THREAD

**Discussion by o-smirnov** [SpheMakh/Stimela#710] [Ideas]
I have realized that a single up-front validation step (before the recipe is run) can't be sufficient. Some inputs for intermediate steps (files etc.) may not exist, {}-substitutions may evaluate to different things at runtime (depending on outputs of previous steps), globs like "{self.prefix}-????-image.fits" can't be expanded into file lists until the wsclean step is actually run, etc. etc.

Therefore, I propose to implement three validation phases for each step:

1. Pre-validation. The recipe has not been run yet, so parameter settings may be invalid. Simple parameters, and those without substitutions, are validated, the rest are marked as "unresolved". This phase is intended to catch obvious errors only.

   When pre-validating a recipe, only validated aliases are propagated up to the steps. Unresolved aliases are not propagated. Child steps are allowed to have unresolved parameters (but they can't be missing required parameters, this can already be detected at this phase)

2. Runtime inputs validation, just before a step is run. Substitutions are done on inputs, and all inputs are validated. Files must exist, etc. A recipe's top-level input aliases (now all validated) are propagated up to its steps.

3. Runtime outputs validation, after a step has been run. Substitutions are done on outputs, and all outputs are validated. Files must exist, etc. A recipe's top-level output aliases are gathered from its steps.

I have a pretty clear idea how to implement this succinctly, but @SpheMakh please try to poke some holes in this logic first.

**Comment by o-smirnov** [comment]
Anyway, I made it so: https://github.com/ratt-ru/scabha/pull/5 https://github.com/ratt-ru/Stimela/pull/712

In the end the fat burned off, and the logic distilled to some checks (for 2 and 3, above) inside ``Step.run()``. As for (1), it's implemented as a ``prevalidate()`` method, but this is called by ``run()`` automatically if needed, and only once.

**Comment by sphemakh** [comment]
I ran the `stimela/tests/test_cubical_recipe.py` file and saw that you don't have `"{  }"` around values that are references, in fact when I tried it I got this error

```
2021-05-05 11:12:25 STIMELA.cubical-image ERROR: error in recipe definition: alias image refers to unknown step '{image'
```

which indicates that this type of substitution is not recognised.

**Reply by o-smirnov** [reply]
Please try these branches: https://github.com/o-smirnov/Stimela/tree/configuratt-oms and https://github.com/o-smirnov/scabha/tree/configuratt-oms, and they work, approve the PRs. Also, may need this: ``pip install git+https://github.com/omry/omegaconf.git``. The master version is much faster, and has some bugs fixed.

**Comment by sphemakh** [comment]
On the substitutions. I think they should be explicit, and should only be relative within the current context. For example, here

https://github.com/ratt-ru/Stimela/blob/bf504702f7b8f5d3ea4c09aea3b305850943cc35/stimela/tests/test_recipe.yml#L50-L52

it should be

```yaml
aliases: 
   msname: steps.selfcal.ms 
   telescope: steps.makems.tel 
```

Also, `self` should refer to the class that the attribute belongs to (in this case, `self` should be a Parameter instance of the parameters `ms`) so this 

https://github.com/ratt-ru/Stimela/blob/bf504702f7b8f5d3ea4c09aea3b305850943cc35/stimela/tests/test_recipe.yml#L16-L18

should be 

```yaml
 ms: 
   dtype: MS 
   implicit: "{inputs.msname}" 
```
This is more intuitive and doesn't require the user to look up what `self` is, it can be treated as it would in python.

**Comment by o-smirnov** [comment]
> On the substitutions. I think they should be explicit, and should only be relative within the current context

Well, an alias is not a substitution, it's a slightly more special beast. An alias can only ever refer to a step's parameter. So in ``steps.selfcal.ms``, ``steps.`` is completely redundant and thus in my view unnecessary. The lack of ``{}`` should cue the user that this is not a "substitution" as such.

> Also, self should refer to the class that the attribute belongs to 

Yeah I feel a little uneasy about ``self``. Anyway there's also difference between OmegaConf DictConfigs and the dataclass objects, don't assume you can just {}-substitute anything anywhere.

Maybe we should do away with ``self`` entirely. Maybe ``{params.msname}``? Again, noting the difference between *inputs* and *outputs* per se (which are parameter schemas), and specific parameter *values*. ``{params.msname}`` refers to a value. So ``params`` would be a namespace containing the current cargo's parameter values?

**Reply by sphemakh** [reply]
> Well, an alias is not a substitution, it's a slightly more special beast. An alias can only ever refer to a step's parameter. So in steps.selfcal.ms, steps. is completely redundant and thus in my view unnecessary. The lack of {} should cue the user that this is not a "substitution" as such.

I see. 

> Yeah I feel a little uneasy about self. Anyway there's also difference between OmegaConf DictConfigs and the dataclass objects, don't assume you can just {}-substitute anything anywhere.

> Maybe we should do away with self entirely. Maybe {params.msname}? Again, noting the difference between inputs and outputs per se (which are parameter schemas), and specific parameter values. {params.msname} refers to a value. So params would be a namespace containing the current cargo's parameter values?

It should be possible to cross-reference to a configs section and children via {}-substitutions without having some global namespace like `self` or `params` that has all the parameters. We want `inputs.foo, outputs.foo, steps.foo.bar`

**Reply by sphemakh** [reply]
Let me implement something and get back to you.

**Reply by o-smirnov** [reply]
The substitution dictionary is assembled here: https://github.com/ratt-ru/Stimela/blob/configuratt/stimela/kitchen/recipe.py#L515

**Reply by o-smirnov** [reply]
Also please note #713. Logfile names also need substitutions...

**Comment by o-smirnov** [comment]
OK, no plan survives contact with the enemy, but check it out @SpheMakh, I now have a working for-loop actually running wsclean over a bunch of MSs.

In the process, I realized that

* It is handy to be able to define multiple recipes in a YML file, and select which one to run from the command line

* It is handy to change Stimela settings from that same YML file

* There are actually FOUR kinds of substitutions going on, and all have their uses. I illustrate this with comments below. Here's my ``recipe.yml``, which I run with ``stimela exec recipe.yml -r img1gc``.

```yml
## this augments the standard 'cabs' config section
cabs:
  wsclean:
    # disable container mode
    image: ''
    ## uncomment this for debugging, to echo command line instead of running wsclean
    # command: echo

## this augments the standard 'opts' config section to tweak logging settings
opts:
  log:
#    dir: logs/log-{datetime}
    dir: logs
    nest: 1

## this augments the standard 'vars' config section, which is completely free-form
## (in this case supplying a variable for use later on)
vars:
  scans: [ '04', '06', '08', '11', '13', '15', '18', '20', '22', '24', '27', '29', '31', '34', 
           '36', '38', '41', '43', '45', '48', '50', '52', '55', '57', '59', '61', '64', '65' ]


## 'clean_image' is not a standard config section, therefore stimela exec treats this as a recipe definition
clean_image:
  name: clean_image
  info: "runs a single deconvolution step"

  aliases:
    ## This a reference of the FIRST kind: an alias is a "hard" link between an inner step parameter and an outer recipe parameter.
    ## this defines an input named "column" that has the same schema as steps.clean.column, and its value is automatically propagated to the 'clean' step
    column: [clean.column]
    
    ## note that all other step parameters (which are not set explicitly) are automatically aliased as if you said
    # clean_niter: [clean.niter]

  defaults:
    column: CORRECTED_DATA
    clean_niter: 50000
    clean_fit_spectral_pol: 4
    clean_nchan: 8

  steps:
    clean: 
      cab: wsclean
      params:
        weight: 'briggs 0'
        size: 10000 
        scale: 0.8asec
        mgain: 0.9
        join_channels: true
        padding: 1.3
        nwlayers_factor: 3
        fit_beam: true
        elliptical_beam: true


## 'img1gc' is not a standard config section, therefore stimela exec treats this as a recipe definition
img1gc:
  name: "img1gc"
  info: "makes 1GC images for all scans"

  for_loop:
    var: scan
    ## This a reference of the SECOND kind: an OmegaConf ${}-substitution. This is handled by OmegaConf at load time (so is kind of "static")
    ## This sets the valuye of "over" to be an exact copy of "vars.scans" above (i.e. a list!)
    over: ${vars.scans}

  inputs:
    scan:
      dtype: str

  steps:
    image: 
      recipe: 
        ## This is a reference of the THIRD kind: a _use clause. This _copies_ the definition of 'single_image' above into the section
        _use: clean_image
        # This is just here to illustrate that the copied-over definition can be augmented by adding fields
        info: "my modified version of single_image"

      params:
        ## These are references of the FOURTH kind: {}-substitutions. This is updated by Stimela at run time (so is fully dynamic!)
        ## The substitution is evaluated as a "dumb" string operation
        clean_ms: '../msdir/1608538564_sdp_l0-Jupiter-scan{recipe.scan}.ms'
        clean_prefix: 'img1/im1-s{recipe.scan}'
        column: DATA
        # clean_niter: 100 # 50000
        # clean_fit_spectral_pol: 2 # 4
        # clean_nchan: 2 # 8


  # another reference of the fourth kind (NB: "params" will probably be renamed to "recipe"?)
  logname: '{name}.scan{params.scan}'
```

**Reply by sphemakh** [reply]
Let's pause adding new features for a bit. I'm testing things, but they are changing too quickly and it's hard to keep track. The test recipes in stimela/tests don't really work and require some decoding, but the infrastructure is now ready for some stress testing with actual recipes which will help us evaluate the best practices for the API.

**Reply by sphemakh** [reply]
I'm adding a YAML recipe that reproduces this example https://github.com/ratt-ru/Stimela/blob/master/examples/simulation_pipeline.py

**Reply by o-smirnov** [reply]
> but the infrastructure is now ready for some stress testing with actual recipes

Couldn't agree more. Except I thought that's where I was at the start of the week. "Jupiter here I come... oh shit, this needs an actual for-loop... oh shit, the logs need to be named intelligently..." Anyway, I *hope* the churn is mostly over. Wsclean was one of fiddlier cabs in the old version, remember, so I find it very encouraging that it runs out of the box now -- no runscript needed!

**Reply by sphemakh** [reply]
I have it running for a single cab and a recipe that doesn't depend on the outputs of a previous step. Can you please push your latest changes with the four types of substitutions

**Reply by o-smirnov** [reply]
> Can you please push your latest changes with the four types of substitutions

That's already in there, and been there for a couple of weeks. I only raised the subject for the purpose of clarification, seeing as  we were talking about substitutions a lot.

I did push some minor changes to configuratt-oms on Stimela and scabha just now. Mostly fixes to how wsclean's _outputs_ are validated (matching globs and such). The business of outputs still feels a little unsettled, but I guess we just need some real-life applications to nail it down.

**Reply by o-smirnov** [reply]
P.S. I updated my Jupiter example recipe above. It is running...

**Reply by sphemakh** [reply]
How do I reference an output product from an earlier step?

**Reply by o-smirnov** [reply]
Example: https://github.com/ratt-ru/Stimela/blob/configuratt/stimela/tests/test_recipe.yml#L79

**Reply by sphemakh** [reply]
I prefer `steps.image.outputs.dirty` but since input and output parameters are not allowed to be the same, having the inputs/outputs is redundant.

**Reply by sphemakh** [reply]
I get a validation error here because of line 100. 

```yaml
 72 recipe:
 73   name: "demo recipe"
 74   info: 'top level recipe definition'
 75   dirs:
 76     input: input
 77     output: output
 78     log: logs
 79   vars:
 80     msname: sphe.ms
 81   aliases:
 82     telescope: makems.tel
 83   defaults:
 84     telescope: kat-7
 85     selfcal_image_size: 1024
 86   steps:
 87       makems:
 88           cab: simms
 89           params:
 90               msname: vars.msname
 91               synthesis: 0.128
 92       plotobs:
 93           recipe:
 94               name: "Plotobs"
 95               info: "Make some basic plots/images from an empty MS"
 96               steps:
 97                   plots:
 98                       cab: shadems
 99                       params:
100                         ms: "{steps.makems.ms}"
101                         xaxis: U
102                         yaxis: V
103                   image:
104                       cab: wsclean
105                       params:
106                           scale: "{recipe.scale}"
107                           ms: "{steps.makems.ms}"
108                           make_psf_only: true
109                           size: [256, 256]
110               aliases:    
111                   image_name: image.prefix
112               inputs:
113                   scale:
114                     dtype: Union[str, float]
115               defaults:
116                   scale: 30asec
```

What did I miss?

**Reply by o-smirnov** [reply]
Well, ``steps`` at line 100 refers to the steps of the "Plotobs" recipe. It has no knowledge of the outer recipe (nor can it -- "Plotobs" would not be self-contained otherwise!)

**Reply by o-smirnov** [reply]
I think the pattern you're looking for is this at the Plotobs recipe level:
```
aliases:
  ms: [plots.ms, image.ms]
```
Saying that plotobs has an ``ms`` input that's passed on to its steps, and then one level up:
```yml
params:
  ms: "{steps.makems.ms}"
recipe:
  name: "Plotobs"
```

**Reply by o-smirnov** [reply]
> but since input and output parameters are not allowed to be the same, having the inputs/outputs is redundant.

Yeah that's sort of why I arrived at a single dict of ``params`` for the set of a particular step's inputs+outputs. It is somewhat painful to keep the values apart. Also as mentioned [here](https://github.com/ratt-ru/Stimela/discussions/714), some outputs need to be validated at the input stage (to make sure they're valid destination filenames). It simplifies the logic to carry them around together.

**Reply by sphemakh** [reply]
> I think the pattern you're looking for is this at the Plotobs recipe level:
> 
> ```
> aliases:
>   ms: [plots.ms, image.ms]
> ```
> 
> Saying that plotobs has an `ms` input that's passed on to its steps, and then one level up:
> 
> ```yaml
> params:
>   ms: "{steps.makems.ms}"
> recipe:
>   name: "Plotobs"
> ```

No bite. I get this 

```bash
2021-05-07 14:12:03 STIMELA ERROR: Error loading test_recipe.yml: Key 'ms' not in 'Step'
	full_key: recipe.steps.params.ms
	reference_type=Any
	object_type=Step
```

**Reply by o-smirnov** [reply]
Seems wrong. Can you add a gist with your current ``test_recipe.yml``?

**Reply by sphemakh** [reply]
https://gist.github.com/SpheMakh/ac8a45deeeaa2ff941635633e4a2474e

**Reply by o-smirnov** [reply]
Ok, the error makes perfect sense. You put the ``params`` section right under steps, so it's trying to interpret it as a "Step" object and refusing:

```yml
  steps: 
      makems:
          cab: simms
          params:
              msname: vars.msname
              synthesis: 0.128
      params:
        ms: "{steps.makems.ms}"
```
You need to put params under plotobs:
```yml
      plotobs:
          params:
            ms: "{steps.makems.ms}"
          recipe:
              name: "Plotobs"
```

**Reply by sphemakh** [reply]
One more error. I'm trying to reference a directory in line 83, the substitution doesn't seem to work leading to a validation error. 

```yaml
 71 recipe:
 72   name: "demo recipe"
 73   info: 'top level recipe definition'
 74   dirs:
 75     input: input
 76     output: output
 77     log: logs
 78   aliases:
 79     telescope: makems.tel
 80     msname: makems.name
 81   defaults:
 82     telescope: kat-7
 83     msname: "{dirs.input}/myms.ms"
 84   steps:
 85       makems:
 86         cab: simms
 87         params:
 88           synthesis: 0.128
```

**Reply by o-smirnov** [reply]
At this line here: https://github.com/ratt-ru/Stimela/blob/configuratt/stimela/kitchen/recipe.py#L574

Add

```
subst1.vars = self.vars
subst1.dirs = self.dirs
```

and see if that works?

**Reply by sphemakh** [reply]
It works, but only I after changed the recipe to be  (see lines 75, 79, and 89)

```yaml
71 recipe:
 72   name: "demo recipe"
 73   info: 'top level recipe definition'
 74   dirs:
 75     input: input
 76     output: output
 77     log: logs
 78   vars:
 79     msname: myms.ms
 80   aliases:
 81     telescope: makems.tel
 82   defaults:
 83     telescope: kat-7
 84   steps:
 85       makems:
 86         cab: simms
 87         params:
 88           synthesis: 0.128
 89           name: "{dirs.input}/{vars.msname}"
 90       plotobs:

```

This is fine, but it would be more convenient to set special dirs globally, something like this

```yaml
dirs: 
  input:
    recipe_indir: true
```

or  

```yaml
 recipe:
   name: "demo recipe"
   info: 'top level recipe definition'
     dirs:
     input: input
     output: output
     log: logs
  recipe_indir: dirs.input
  recipe_outdir: dirs.output
```

**Comment by o-smirnov** [comment]
@SpheMakh please sync up both Stimela and scabha, I pushed some minor tweaks I needed to do for Jupiter. In particular, I added the ``-s`` option to exec to run a subset of steps.

Here's my latest Jupiter recipe: https://gist.github.com/o-smirnov/d39775215a9674595a37d4d5e3f9d889

I realized that single-step subrecipes (such as what I had initially for e.g. making an image) were an unnecessary complication. Much simpler to define standard step templates under ``lib.steps``, and insert them into the recipe via ``_use``. See my recipe for how nicely this works for wsclean (there's even "inheritance" going on, so that I only need to define common wsclean settings in one place).

**Reply by sphemakh** [reply]
This is very nice! https://gist.github.com/o-smirnov/d39775215a9674595a37d4d5e3f9d889#file-recipe2-yml-L158

**Comment by o-smirnov** [comment]
@SpheMakh please update both scabha and Stimela, I have cleaned up and streamlined the substitution mechanism quite a bit.

Also, after much circling around the issue, I've decided to propose the concept of recipe *variables* (in addition to, and similar to, inputs and outputs, which are *parameters*. The direct analogy is a function's parameters vs. local variables.) I feel the concept has been knocking on the door anyway. For example, in ``for_loop`` kind of recipe, the loop index is a variable. Input/output dirs are essentially variables (though some recipes could choose to treat them as parameters, too). So, I propose an ``assign`` section which unifies all this. 

The recipe writer doesn't need to use variables, it's an optional feature. The point of them is that they allow for cleaner and more flexible substitutions, and let you do things like set up naming conventions in one place. Like so -- read the comments in the YML:

```yml
opts:
  log:
    dir: logs-{config.run.datetime}    # note this is new -- logfile names can do substitutions!
    nest: 3
    symlink: logs                  # this is also new. Akin to the caracal logs symlink, which I've grown to like a lot


cubical_image:
  name: "cubical_image"
  info: 'does one step of cubical, followed by one step of imaging'

  # an "assign" section just assigns a bunch of variables, which then show up in the "recipe" substitution namespace
  # (along with a recipe's parameters -- if there's a name clash between variables and parameters, an error is thrown) 
  assign:
    # nothing special about "dir", it's just a name, but the recipe can now use a {recipe.dir.out} in substitutions
    dir: 
      out: 'output'
    x: 1
    y: 2
    # This recipe is a for-loop over the variable "loop" -- so this forms up another variable based on the current value of "loop".
    # Just showing off substitutions here. But this is handy for use in filenames.
    # BTW I noticed "-" is a legit character in attribute names, so just playing with it here.
    loop-name: "s{recipe.loop:02d}"
    # Next, we form up a variable based on:
    #   * dir.out defined above
    #   * loop-name defined above
    #   * "{info.suffix}" -- "info" is a namespace with info about the current recipe step (for "image-1", suffix is "1")
    # The point of this construct is that I can now have steps like "image-1", "image-a", "image-deep", and
    # use the same filename convention throughout, without changing any step parameters
    image-prefix: "{recipe.dir.out}/im{info.suffix}-{recipe.loop-name}/im{info.suffix}-{recipe.loop-name}"
    # "log" is the only variable that gets special treatment. Assignments to "log" get propagated into opts.log, i.e. affect logfile naming
    # the below will change log file names as "loop-name" changes, causing every iteration of the "scan" for-loop to produce
    # its own logfiles 
    log:
      dir: logs-{config.run.datetime}
      # "{info.fqname}" is the fully-qualified name of the current step, i.e. "recipe_name.step_name"
      name: log-{recipe.loop-name}-{info.fqname}.txt

  for_loop:  # this makes a for-loop, this is as before. "loop" becomes a variable
    var: loop
    over: [1,2,3]

  aliases:
    ms: [calibrate.ms, image-1.ms]

  steps: 
    calibrate: 
        cab: cubical
    image-1:
        cab: myclean
        params:
          prefix: "{recipe.image-prefix}"
        # just to demonstrate that a step can update a recipe's variables. This variable is not used anywhere here though.
        assign:
          foo: "bar"
    image-deep:
        cab: myclean
        params:
          # note that {recipe.image-prefix} will have changed, as the "scan" and step name changes
          prefix: "{recipe.image-prefix}"
          # ...
        assign:
          foo: "bar"
```

Note also that substitution namespaces are *not quite* the same thing as the YML config namespace anymore, since their contents change dynamically as you run the recipe. At the moment the main one is formed up here: https://github.com/ratt-ru/Stimela/blob/configuratt/stimela/kitchen/recipe.py#L594. The following top-level names are currently used (but I'm not too attached to the names, so we can discuss):

* ``config`` contains the entire configuration dict
* ``recipe`` contains the recipe's parameters and variables
* ``info`` contains some naming info about the current step (name, fully-qualified name, name suffix if any, etc.)
* ``current`` contains the parameters of the current step
* ``previous`` contains the parameters of the previous step
* ``steps.step_label`` contains the parameters of all (previously defined) steps, using the step label as the attribute
