### DISCUSSION TITLE
Aliases and defaults

### DISCUSSION THREAD

**Discussion by o-smirnov** [SpheMakh/Stimela#715] [Ideas]
Looking at this chunk of my recipe:
```yml
  inputs:
    scan:
      dtype: str
    scan_list:
      dtype: List[str]
    sol_type:
      dtype: str
      choices: [kk, kkde, kkde2]

  defaults:
    scan_list: ${vars.all_scans}
    sol_type: kkde
    sol_k_int: 1
```
...I find myself slightly offended by the repetition. And yes, I remember that making a separate ``defaults`` section was my suggestion. And I still think this is a good idea to have all the defaults in one place when many inputs are involved.

However, in the spirit of democracy and pluralistic ways of skinning felines, it occurs to me that we could have our cake and eat it. Reinstate an optional ``default`` keyword in the Parameter schema, and keep the ``defaults`` section at parent level. The outer defaults then override the internal defaults if provided. What do you think @SpheMakh?

**Comment by sphemakh** [comment]
I was about to suggest the same thing!

**Reply by o-smirnov** [reply]
Good, I shall make it so then!

**Comment by o-smirnov** [comment]
I should probably do the same for aliases. Where my recipe now says

```yml
  inputs:
    ...

  aliases:
    sol_k_tint: [selfcal.k_time_int, selfcal_res.k_time_int]
    sol_k_fint: [selfcal.k_freq_int, selfcal_res.k_freq_int]

  defaults:
    sol_k_tint: 1
    sol_k_fint: 1024
```

it could say

```yml
  inputs:
    ...
    sol_k_tint: 
      aliases: [selfcal.k_time_int, selfcal_res.k_time_int]
      default: 1
    sol_k_fint: 
      aliases: [selfcal.k_freq_int, selfcal_res.k_freq_int]
      default: 1024
```
